apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  annotations:
    apiconnect-operator/cp4i: 'true'
  labels:
    backup.apiconnect.ibm.com/component: apiconnectcluster
  name: medium-cdt
  namespace: cp4i
spec:
  analytics:
    mtlsValidateClient: true
  license:
    accept: true
    license: L-PDZK-TWDH97
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  portal:
    mtlsValidateClient: true
  profile: n1xc16.m72
  version: 12.1.0.0
  storageClassName: ocs-storagecluster-ceph-rbd
